name: CI - Web + E2E + Android + Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  web:
    name: Web Build & Unit/Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Unit/Integration tests
        run: pnpm --filter client test -- --run

      - name: Type check
        run: pnpm --filter client type-check

      - name: Build web
        run: pnpm build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: dist/**

  e2e:
    name: Playwright E2E (Game Flow)
    runs-on: ubuntu-latest
    needs: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright E2E (preview server)
        working-directory: src/client
        run: pnpm test:e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: src/client/playwright-report/**

  android:
    name: Android Debug APK
    runs-on: macos-14
    needs: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Download web dist
        uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: dist

      - name: Setup Java 21
        run: |
          brew install openjdk@21
          echo "JAVA_HOME=/opt/homebrew/opt/openjdk@21" >> $GITHUB_ENV
          echo "/opt/homebrew/opt/openjdk@21/bin" >> $GITHUB_PATH

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses & install components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;34.0.0"

      - name: Capacitor sync android
        run: pnpm exec cap sync android

      - name: Assemble Debug APK
        run: ./android/gradlew -p android assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/*.apk

  desktop:
    name: Desktop (macOS) Build
    runs-on: macos-14
    needs: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Download web dist
        uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: dist

      - name: Electron dir build
        run: pnpm exec electron-builder --dir

      - name: Electron dmg/zip (unsigned)
        run: pnpm exec electron-builder --mac dmg zip -c.mac.identity=null

      - name: Upload desktop artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desktop-mac
          path: dist-electron/**

