name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]
  workflow_dispatch:
    inputs:
      generate_assets:
        description: 'Generate fresh assets with AI'
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-web:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    # Only deploy if CI passed and it's a push to main (not PRs)
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event.workflow_run.conclusion == 'success' && 
       github.event.workflow_run.event == 'push')
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate fresh content (if requested)
        if: github.event_name == 'workflow_dispatch' && inputs.generate_assets
        run: |
          echo "🎨 Generating fresh game content..."
          npm run generate-content || echo "⚠️  Content generation failed, using committed files"
          npm run generate-sprites || echo "⚠️  Sprite generation failed, using committed files"
          npm run generate-hud || echo "⚠️  HUD generation failed, using committed files"
          npm run generate-ui-icons || echo "⚠️  UI icon generation failed, using committed files"
          npm run asset-pipeline || echo "⚠️  Asset pipeline failed, using committed files"
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        continue-on-error: true
      
      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist/
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
