name: Release

on:
  workflow_run:
    workflows: ["Deploy"]
    types: [completed]
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write

jobs:
  auto-release:
    name: Automated Release
    runs-on: ubuntu-latest
    # Only release after successful deploy
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24
          extra_plugins: |
            @semantic-release/changelog@6
            @semantic-release/git@10
            conventional-changelog-conventionalcommits@8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create GitHub Release if new version
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.semantic.outputs.new_release_version }}
          name: v${{ steps.semantic.outputs.new_release_version }}
          body: ${{ steps.semantic.outputs.new_release_notes }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Trigger platform builds if new release
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const version = 'v${{ steps.semantic.outputs.new_release_version }}';
            console.log(`🚀 Triggering platform builds for ${version}`);
            console.log('⚠️  NOTE: Platform builds have NOT been manually tested!');
            console.log('📋 See .github/PLATFORM_BUILD_TESTING.md for testing checklist');
            
            try {
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'platform-builds.yml',
                ref: 'main',
                inputs: {
                  version: version
                }
              });
              console.log('✅ Platform builds workflow triggered successfully');
            } catch (error) {
              console.error('❌ Failed to trigger platform builds:', error);
              // Don't fail the job if this fails
            }
