name: Semantic Release

# Automated versioning and releases using semantic-release
# Analyzes commit messages (feat:, fix:, BREAKING CHANGE:) and creates releases

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24
          extra_plugins: |
            @semantic-release/changelog@6
            @semantic-release/git@10
            conventional-changelog-conventionalcommits@8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Trigger mobile build for release
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const version = 'v${{ steps.semantic.outputs.new_release_version }}';
            
            console.log(`🚀 Triggering mobile-primary workflow for ${version}`);
            
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'mobile-primary.yml',
              ref: 'main'
            });
      
      - name: Release summary
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo "## 🎉 Release v${{ steps.semantic.outputs.new_release_version }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.semantic.outputs.new_release_notes }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Mobile build triggered automatically" >> $GITHUB_STEP_SUMMARY
