name: Web Build & Deploy

# DEPRECATED: This workflow is maintained for backward compatibility.
# New builds should use the "Build All Platforms" workflow which is more efficient.

# Web platform flow: Build → Deploy → E2E test DEPLOYED URL

on:
  workflow_run:
    workflows: ["Integration Tests"]
    types: [completed]
    branches: [main]
  workflow_dispatch:
    inputs:
      generate_assets:
        description: 'Generate fresh assets with AI'
        type: boolean
        default: false

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: web-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event.workflow_run.conclusion == 'success' && 
       github.event.workflow_run.head_branch == 'main')
    
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate fresh assets (if requested)
        if: github.event_name == 'workflow_dispatch' && inputs.generate_assets
        run: |
          echo "🎨 Generating fresh game content..."
          npm run generate-content || echo "⚠️  Content generation failed"
          npm run generate-sprites || echo "⚠️  Sprite generation failed"
          npm run generate-hud || echo "⚠️  HUD generation failed"
          npm run generate-ui-icons || echo "⚠️  UI icons failed"
          npm run asset-pipeline || echo "⚠️  Asset pipeline failed"
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        continue-on-error: true
      
      - name: Build web
        run: npm run build
        env:
          NODE_ENV: production
      
      - name: Report bundle size
        run: |
          BUNDLE_SIZE=$(du -sb dist | cut -f1)
          BUNDLE_MB=$(echo "scale=2; $BUNDLE_SIZE / 1024 / 1024" | bc)
          echo "Bundle size: ${BUNDLE_MB}MB"
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: web-build-${{ github.sha }}
          path: dist/
          retention-days: 7

  deploy-web:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-web
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Download build
        uses: actions/download-artifact@v6
        with:
          name: web-build-${{ github.sha }}
          path: dist/
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist/
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
      - name: Save deployed URL
        run: echo "DEPLOYED_URL=${{ steps.deployment.outputs.page_url }}" >> $GITHUB_ENV

  e2e-web:
    name: E2E Tests (Deployed Web)
    runs-on: ubuntu-latest
    needs: deploy-web
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright
        run: npx playwright install --with-deps
      
      - name: Get deployment URL
        id: get-url
        run: |
          # Get the GitHub Pages URL
          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          PAGES_URL="https://${{ github.repository_owner }}.github.io/${REPO_NAME}/"
          echo "PAGES_URL=${PAGES_URL}" >> $GITHUB_OUTPUT
          echo "Testing deployed URL: ${PAGES_URL}"
      
      - name: Wait for deployment
        run: |
          echo "Waiting for deployment to be ready..."
          sleep 30
          curl -f "${{ steps.get-url.outputs.PAGES_URL }}" || sleep 30
      
      - name: Run E2E tests against DEPLOYED site
        run: npm run test:e2e
        env:
          BASE_URL: ${{ steps.get-url.outputs.PAGES_URL }}
      
      - name: Upload E2E report
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: e2e-web-report-${{ github.sha }}
          path: playwright-report/
          retention-days: 7
      
      - name: E2E Summary
        run: |
          echo "## ✅ E2E Tests (Web)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Tested DEPLOYED site at: ${{ steps.get-url.outputs.PAGES_URL }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "This tests the actual production deployment, not local builds!" >> $GITHUB_STEP_SUMMARY

  visual-tests:
    name: Visual Regression (Deployed Web)
    runs-on: ubuntu-latest
    needs: deploy-web
    timeout-minutes: 20
    
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      
      - name: Get deployment URL
        id: get-url
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          PAGES_URL="https://${{ github.repository_owner }}.github.io/${REPO_NAME}/"
          echo "PAGES_URL=${PAGES_URL}" >> $GITHUB_OUTPUT
      
      - name: Wait for deployment
        run: sleep 30
      
      - name: Run visual tests against DEPLOYED site
        run: npm run test:visual
        env:
          BASE_URL: ${{ steps.get-url.outputs.PAGES_URL }}
      
      - name: Upload visual results
        uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: visual-test-results-${{ github.sha }}
          path: |
            test-results/
            playwright-report/
          retention-days: 7
